### PR TITLE
You probably don't want to fork this repo yet!

### PR DESCRIPTION
**Pull request by hughrawlinson**
Hi! Sorry this is a PR, but you've got issues turned off. Just want to let you know that my copy of this repo (which you forked) doesn't contain a valid app - it was purely for me to test the app store, which I'm working on. The python code and the manifest file are both not valid. Working on finalizing the manifest format asap, but to write an app, you should follow the documentation [here](https://tildagon.badge.emfcamp.org/tildagon-apps/development/) rather than starting with this code.

### CODE REVIEW

**Comment by hughrawlinson** [comment]
tag for visibility: @robotgeoff

**Comment by DamTobor** [comment]
Hi Hugh. I think we have now followed the instructions and hopefully our app is discoverable and installable.

**Comment by RichardoC** [comment]
Can we get https://tildagon.badge.emfcamp.org/tildagon-apps/publish/#instructions updated then as it explicitly says to fork this repo as an example?

**Comment by hughrawlinson** [comment]
It's ok to fork now!

**Pull request closed without merging**
